name: 'Workflow using Echo Message workflow'
on: [push, pull_request, workflow_dispatch]

jobs:
  call-echo-message:
    uses: felipevalimstudent/workflow-actions-server/.github/workflows/reusable-echo.yml@main
    with:
      message: 'Hello, world!'