name: 'Workflow using Install jq workflow'
on: [push, pull_request, workflow_dispatch]

jobs:
  install-jq:
    uses: felipevalimstudent/workflow-actions-server/.github/workflows/reusable-install-jq.yml@main