name: 'Install nmon'
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    environment: production 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: List files
      run: ls -al
    - name: Install Nmon
      uses: felipevalimstudent/workflow-actions-server/.github/composite-action@main
