name: 'Workflow using Checkout and Install nmon action'
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nmon
      uses: felipevalimstudent/workflow-actions-server/.github/actions/composite-action@main